### PR TITLE
Add GitHub actions

### PR DESCRIPTION
**Pull request by bwisn**
This PR adds GitHub Actions with workflow that builds and signs firmware automatically on tags, pushes to main and PR to main.

### CODE REVIEW

**Comment by Gissio** [comment]
This is really cool!

Could it be that it doesn't erase old tools/*.bin files?

If that is the case, could you please add this functionality and push the change?

**Comment by bwisn** [comment]
What do you mean by saying that it "doesn't erase old tools/*.bin" files?
It doesn't alter the repository in any way. It just clones the repository inside a container, builds it and publishes the artifacts (which are the .bin files)

**Comment by Gissio** [comment]
I'm not well acquainted with GitHub actions, that's why I asked!

So no files are pushed to the repository, great!

**Comment by Gissio** [comment]
I just pushed a change, and the action executed correctly. Could you confirm everything works as expected?

**Comment by bwisn** [comment]
Yes, it looks okay!

**Comment by Gissio** [comment]
It works great and is very useful. Thanks for your wonderful PR!

**Pull request merged**
